format = """\
$username\
$directory\
"""

add_newline = false 

[username]
format = "[](white)[$user]($style)[](white bg:green)"

style_user = "purple bold bg:white"
style_root = "purple bold bg:white"

show_always = true
[directory]
format = "[ $path]($style)[ ](green)"

style = "white bg:green"

truncation_length = 3
truncation_symbol = ".../"

#    
